### ISSUE TITLE
Generalize Colour Argument

### ISSUE THREAD

**Issue by PythonFZ** [zincware/ZnVis#4]
I think it would be beneftitial to allow for `colour=[255, 133, 64]` or `colour="FFEE23"`
For example use https://colormap.readthedocs.io/en/latest/quickstart.html#list

https://github.com/zincware/ZnVis/blob/d17c3f16a71daba2146ab50eafc720bf0ced5b1d/examples/simple_spheres.py#L33

<sup><sup>Also maybe consider rename `colour` to `color`?</sup></sup>

**Comment by SamTov** [comment]
I could do this and then take a Union of colour arguments or I could demand that people pass one type and use the conversion beforehand. I think when people want quite complex colour arguments they may define a complete material or something of the sort. I would prefer to only take one type of argument though.

As for the name I will stick with British English.

**Comment by SamTov** [comment]
There are also extensions that can be made for handling materials and textures so complex colouring can be achieved. The question is always do we add the functionality and handling or push it onto the user. I'd be happy to introduce a graphics class or something and add some handling there.
